#!/usr/bin/env python3
"""
build_insole.py — turn an analysis result into a printable insole model.

Reads insole_spec.json (produced by analysis/interpret.py) and writes a
parametric OpenSCAD file with the design directives *baked in*:

  relief_window_zone  -> a recessed relief pocket placed under that foot zone
  relief_window       -> 'aggressive' => deeper + wider pocket, else 'standard'
  posting             -> medial / lateral wedge (pronation / supination support)
  cushion_priority    -> 'heel' => thicker heel build-up
  heel_cup            -> 'deep'  => raised heel rim (if present)

This closes the loop: measure -> interpret -> **the insole designs itself**.
If OpenSCAD is on PATH it also renders relief_insole.stl + .png.

    python build_insole.py --spec ../sample/results/insole_spec.json --out .

The generated shape is a generic footbed for illustration. For a true-fit insole,
boolean the relief pocket + post into your SCANNED orthotic instead (see
../docs/insole_print_spec.md) — this script shows exactly where they go.
NOT a medical device.
"""
import argparse, json, os, shutil, subprocess

# normalized foot frame (x: medial->lateral, y: heel->toe) — matches the analysis
ZONE_XY = {
    "heel_med": (.35, .08), "heel_lat": (.65, .08), "midfoot": (.50, .45),
    "met1": (.30, .72), "met3": (.50, .74), "met5": (.70, .72),
    "hallux": (.28, .92), "toes": (.55, .95),
}
L, W = 255.0, 95.0     # insole length / max width (mm)


def clamp(v, lo, hi):
    return max(lo, min(hi, v))


def scad(spec):
    zone = spec.get("relief_window_zone", "heel_med")
    zx, zy = ZONE_XY.get(zone, (.35, .08))
    aggressive = "aggres" in str(spec.get("relief_window", "")).lower()
    relief_r = 22.0 if aggressive else 16.0
    relief_d = 3.5 if aggressive else 2.0
    heel_cushion = spec.get("cushion_priority") == "heel"
    heel_t = 9.0 if heel_cushion else 6.5
    base_t = 4.0
    posting = spec.get("posting", "neutral")
    post_h = 4.0 if posting in ("medial", "lateral") else 0.0
    heel_cup = 3.0 if str(spec.get("heel_cup", "")).startswith("deep") else 0.0

    rx = clamp(zx * W, relief_r + 3, W - relief_r - 3)
    ry = clamp(zy * L, relief_r + 3, L - relief_r - 3)
    top_z = heel_t if ry < L * 0.45 else base_t     # heel region is taller

    return f"""// AUTO-GENERATED by build_insole.py — DO NOT hand-edit.
// Design directives baked in from insole_spec.json:
//   relief zone = {zone}   ({'aggressive' if aggressive else 'standard'} relief)
//   posting     = {posting}
//   cushion     = {'heel' if heel_cushion else 'balanced'}
//   heel cushion material = {spec.get('heel_cushion', 'standard')} (print heel in soft TPU 85A)
// Print: firm TPU 95A shell + soft TPU 85A heel/relief on the H2D (dual material).
$fn = 72;

L = {L}; W = {W};
base_t = {base_t}; heel_t = {heel_t};
relief_x = {rx:.1f}; relief_y = {ry:.1f}; relief_r = {relief_r}; relief_d = {relief_d};
post_h = {post_h}; heel_cup = {heel_cup};

module outline2d() {{
    hull() {{
        translate([32, 30])  circle(r=30);   // heel
        translate([30, 120]) circle(r=34);   // arch (medial)
        translate([48, 205]) circle(r=44);   // forefoot
        translate([48, 240]) circle(r=30);   // toes
    }}
}}

module heel_region() translate([-1, -1, 0]) cube([W + 2, L * 0.42, heel_t + heel_cup + 1]);

module body() {{
    // base plate everywhere + extra heel build-up over the heel only
    linear_extrude(height = base_t) outline2d();
    intersection() {{ linear_extrude(height = heel_t) outline2d(); heel_region(); }}
    if (post_h > 0) intersection() {{
        // {posting} wedge: full height at that edge -> 0 at centerline
        hull() {{
            translate([{ '2' if posting=='medial' else 'W-3' }, 45, base_t]) cube([1, 95, post_h]);
            translate([W/2, 45, base_t]) cube([1, 95, 0.1]);
        }}
        linear_extrude(height = base_t + heel_t + post_h) outline2d();
    }}
    if (heel_cup > 0) intersection() {{      // raised heel rim
        difference() {{
            linear_extrude(height = heel_t + heel_cup) outline2d();
            translate([0, 0, heel_t]) linear_extrude(height = heel_cup + 1) offset(r = -7) outline2d();
        }}
        heel_region();
    }}
}}

difference() {{
    body();
    // relief window: recess into the top surface under the hot spot
    translate([relief_x, relief_y, ({top_z} ) - relief_d + 0.01])
        cylinder(r1 = relief_r * 0.7, r2 = relief_r, h = relief_d + 1);
}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default="../sample/results/insole_spec.json")
    ap.add_argument("--out", default=".")
    ap.add_argument("--name", default="relief_insole")
    args = ap.parse_args()

    with open(args.spec) as f:
        data = json.load(f)
    spec = data.get("chosen", data)
    os.makedirs(args.out, exist_ok=True)
    scad_path = os.path.join(args.out, f"{args.name}.scad")
    with open(scad_path, "w") as f:
        f.write(scad(spec))
    print(f"-> {scad_path}")
    print(f"   relief@{spec.get('relief_window_zone')} · {spec.get('relief_window')} · "
          f"posting={spec.get('posting')} · cushion={spec.get('cushion_priority')}")

    exe = shutil.which("openscad") or (
        r"C:\Program Files\OpenSCAD\openscad.exe"
        if os.path.exists(r"C:\Program Files\OpenSCAD\openscad.exe") else None)
    if exe:
        for ext, extra in (("stl", []), ("png", ["--imgsize=820,900", "--viewall",
                                                 "--autocenter", "--colorscheme=Tomorrow"])):
            out = os.path.join(args.out, f"{args.name}.{ext}")
            subprocess.run([exe, "-o", out, *extra, scad_path],
                           check=False, capture_output=True)
            if os.path.exists(out):
                print(f"-> {out}")
    else:
        print("   (OpenSCAD not found — open the .scad and F6 -> Export STL)")


if __name__ == "__main__":
    main()
